// <auto-generated />
using Car_API_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car_API_Project.Migrations
{
    [DbContext(typeof(Car_API_ProjectContext))]
    partial class Car_API_ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Car_API_Project.Models.Car", b =>
                {
                    b.Property<int>("Car_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Car_Date")
                        .HasColumnType("int");

                    b.Property<string>("Car_Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Car_Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Car_ID");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
